global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "fastapi_system"
    static_configs:
      - targets: ["localhost:8001"]